apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cascade
resources:
  - namespace.yaml
  - peer-policy.yaml
  - services.yaml
  - statefulsets.yaml
  - disruption-budget.yaml
  - network-policy.yaml
  - monitoring.yaml
  - prometheus-rules.yaml
configMapGenerator:
  - name: cascade-grafana-dashboard
    files:
      - cascade.json=dashboards/cascade.json
    options:
      labels:
        grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: cascade
      app.kubernetes.io/part-of: cascade
    includeSelectors: true
